# Generated by Django 4.1.5 on 2023-03-10 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signup',
            new_name='signup_table',
        ),
    ]
