# Generated by Django 4.1.5 on 2023-03-11 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_rename_name_login_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='codoid_login',
        ),
    ]
